apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: kps
  repo:  https://prometheus-community.github.io/helm-charts
  releaseName: charts/kube-prometheus-stack
  namespace: grafana
  version: 67.10.0
